# -*- coding: utf-8 -*-
"""diagnosis_wizard.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1la7CmMnrsLyrp0blLe0juCVpxgBoV1xg
"""

# Import required libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
import plotly.express as px
import streamlit as st

# Create an extensive dataset of symptoms and corresponding diagnoses
data = {
    'Symptoms': [
      "Cough, Fever",
      "Headache, Fatigue",
      "Sore Throat, Chills",
      "Runny Nose",
      "Shortness of Breath, Chest Pain",
      "Nausea, Vomiting",
      "Body Aches, Fever",
      "Watery Eyes",
      "Dizziness, Nausea",
      "Fever, Sore Throat",
      "Cough, Chest Congestion",
      "Rash, Itching",
      "Joint Pain, Muscle Pain",
      "Headache, Runny Nose",
      "Cough, Shortness of Breath",
      "Loss of Taste, Loss of Smell",
      "Frequent Urination, Burning Sensation",
      "Abdominal Pain, Diarrhea",
      "Fever, Body Aches",
      "Sneezing, Fatigue",
      "Chest Tightness, Wheezing",
      "Back Pain, Fatigue",
      "Sore Muscles, Fever",
      "Itchy Eyes, Sneezing",
      "Nasal Congestion, Headache",
      "Dry Cough, Shortness of Breath",
      "Joint Swelling, Redness",
      "Mild Fever, Sore Throat",
      "Nausea, Abdominal Pain",
      "Chest Discomfort, Heartburn",
      "High Fever, Weakness",
      "Persistent Cough, Weight Loss",
      "Frequent Headaches, Sensitivity to Light",
      "Severe Pain, Numbness",
      "Breathing Difficulties, Rapid Heartbeat",
      "Confusion, Memory Loss",
      "Swollen Glands, Fatigue",
      "Fever, Vomiting",
      "Difficulty Swallowing, Hoarse Voice",
      "Joint Stiffness, Limited Movement",
      "Extreme Fatigue, Unexplained Weight Gain",
      "Chest Congestion, Sore Throat",
      "Muscle Weakness, Tremors",
      "Difficulty Breathing, Blue Lips",
      "Unexplained Bruising, Fatigue",
      "Seizures, Loss of Consciousness",
      "Blood in Urine, Abdominal Pain",
      "Blurred Vision, Eye Pain",
      "Excessive Thirst, Frequent Hunger",
      "Sudden Weight Loss, Blurred Vision",
      "Coughing Blood, Chest Pain",
      "Swelling in Legs, Shortness of Breath",
      "Sudden High Fever, Chills",
      "Difficulty Speaking, Drooping Face",
      "Nausea, Sensitivity to Light",
      "Pale Skin, Fatigue",
      "Muscle Cramps, Dehydration",
      "Chest Pain, Anxiety",
      "Memory Loss, Confusion",
      "Lack of Coordination, Slurred Speech",
      "Frequent Infections, Fatigue",
      "Hair Loss, Dry Skin",
      "Bloating, Abdominal Cramps",
      "Difficulty Concentrating, Restlessness",
      "Vision Problems, Eye Redness",
      "Irregular Heartbeat, Dizziness",
      "Chest Pressure, Arm Pain",
      "Nasal Discharge, Sneezing",
      "Painful Urination, Lower Back Pain",
      "Abdominal Bloating, Constipation",
      "Sweating, Nausea",
      "Rapid Weight Gain, Swollen Feet",
      "Muscle Weakness, Fatigue",
      "Back Pain, Leg Numbness",
      "Difficulty Swallowing, Weight Loss"
],
'Diagnosis': [
      "Common Cold",
      "Migraine",
      "Strep Throat",
      "Allergies",
      "Heart Attack",
      "Food Poisoning",
      "Influenza",
      "Pink Eye",
      "Vertigo",
      "Tonsillitis",
      "Bronchitis",
      "Dermatitis",
      "Arthritis",
      "Sinusitis",
      "Pneumonia",
      "COVID-19",
      "Urinary Tract Infection",
      "Gastroenteritis",
      "Flu",
      "Seasonal Allergies",
      "Asthma",
      "Fibromyalgia",
      "Influenza",
      "Hay Fever",
      "Sinusitis",
      "COVID-19",
      "Rheumatoid Arthritis",
      "Common Cold",
      "Appendicitis",
      "Acid Reflux",
      "Viral Infection",
      "Tuberculosis",
      "Migraine",
      "Sciatica",
      "Panic Attack",
      "Alzheimer's Disease",
      "Mononucleosis",
      "Gastroenteritis",
      "Laryngitis",
      "Osteoarthritis",
      "Hypothyroidism",
      "Tonsillitis",
      "Parkinson's Disease",
      "Cyanosis",
      "Leukemia",
      "Epilepsy",
      "Kidney Stones",
      "Glaucoma",
      "Diabetes",
      "Hyperthyroidism",
      "Pulmonary Embolism",
      "Heart Failure",
      "Malaria",
      "Stroke",
      "Migraine",
      "Anemia",
      "Heat Exhaustion",
      "Panic Attack",
      "Dementia",
      "Stroke",
      "Immunodeficiency",
      "Hypothyroidism",
      "Irritable Bowel Syndrome",
      "Attention Deficit Hyperactivity Disorder",
      "Conjunctivitis",
      "Arrhythmia",
      "Heart Attack",
      "Common Cold",
      "Urinary Tract Infection",
      "Irritable Bowel Syndrome",
      "Anxiety",
      "Edema",
      "Chronic Fatigue Syndrome",
      "Herniated Disc",
      "Esophageal Cancer"
  ]
}

# Create a DataFrame using the dataset
medical_data = pd.DataFrame(data)

# Split data into symptoms (features) and diagnoses (labels)
X = medical_data['Symptoms']
y = medical_data['Diagnosis']

# Convert symptoms into numerical representations
vectorizer = CountVectorizer()
X_vectorized = vectorizer.fit_transform(X)

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_vectorized, y, test_size=0.2, random_state=42)

# Create and train our diagnosis machine using the powerful Naive Bayes algorithm
diagnosis_machine = MultinomialNB()
diagnosis_machine.fit(X_train, y_train)

# Streamlit app for user interaction
st.title("🏥 Medical Diagnosis Helper")
st.write("Hello there! Let's harness the power of technology to assist doctors in diagnosing patients with accuracy and efficiency.")

# Allow the user to input symptoms
user_input = st.text_area("🤒 Kindly provide your symptoms (at least two, separated by commas):", "")

# Transform the user's symptoms into a format the machine understands
user_input_vectorized = vectorizer.transform([user_input])

# Predict potential diagnosis based on the user's symptoms
predicted_diagnosis = diagnosis_machine.predict(user_input_vectorized)

st.write("Based on the symptoms you provided, our tool suggests that you might have:", predicted_diagnosis[0])

# Visualization using Plotly
# Exploring Diagnosis Distribution
diagnosis_count = medical_data['Diagnosis'].value_counts()

# Bar Chart Visualization
bar_fig = px.bar(diagnosis_count, x=diagnosis_count.index, y=diagnosis_count.values,
title='📊 Diagnosis Distribution')
st.plotly_chart(bar_fig)

# Treemap Visualization
treemap_fig = px.treemap(diagnosis_count, path=[diagnosis_count.index], values=diagnosis_count.values,
title='📊 Diagnosis Distribution (Treemap)')
st.plotly_chart(treemap_fig)

st.write("💡 This tool is a reliable ally to doctors, analyzing symptoms and providing intelligent diagnostic recommendations. Imagine having a smart companion in the medical field!")